---
# favicon, can take any image type
favicon: 'favicon.ico'

# URL to the website
website_url: 'https://jessebot.work'

# domain name, or whatever you want the tab in the browser to say
website_title: "Jesse's resume"

# set to false to remove fork me banner in uppper right corner
fork_me: true

# image shown at the front of the page, this should be in /static/img
profile_image: 'my_picture.png'

# image alt text
profile_image_alt: 'Portrait selfie of a 32 year old person with an olive skin tone. They have an undercut and medium legnth blue hair parted to the side. They are smiling and wearing a black shirt.'

# Your name
name: 'Jesse Hitch'

# Pronouns
pronouns: 'they/them'

# blurb about yourself
blurb: "You can probably call me if there's a problem with Kubernetes, CI/CD, a Python app, or you need help with most things to do with the web. I also put too much effort into terminal based interfaces, and if you let me, will draw pictures of tech stuff."

# Job Title
occupation: 'Senior Reliability Engineer'
# Skills - what you're good at.
skills:
  - linux
  - devops
  - python
  - kubernetes
  - cicd

# This is for a section to humanize the user
likes:
  - comfy couches
  - videogames
  - tamagotchis

# social links you want to display on the profile
social_links:
  github:
    # Full URL to your social link
    URL: 'https://github.com/jessebot'
    # can be any glyph in nerdfonts
    icon: 'nf-fa-github_alt_link'

  # gitlab is optional
  # gitlab:
  #   URL: 'https://gitlab.com/jessebot'
  #   icon: "nf-fa-gitlab"

  linkedin:
    URL: 'https://www.linkedin.com/in/jesse-hitch'
    icon: 'nf-fa-linkedin_square'

  # mastodon is optional
  mastodon:
    URL: 'https://social.smallhack.org/@jessebot'
    icon: "nf-fa-mastodon"

  # fedi is optional
  # fedi:
  #   URL: 'https://social.smallhack.org/@jessebot'
  #   icon: "nf-fa-fediverse"

# this can be from any provider, but has to download a PDF file
resume_pdf_URL: "https://docs.google.com/document/d/1O-qsyVP444QeaBi9EwygDlGzIWvMMUJP80cPsk2Z6lg/export?format=pdf"
